### ISSUE TITLE
TypeError as script processes dfxml.xml

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#16]
When running bc_to_aspace.py, everything seemed to work right until the script parsed the dfxml file, when it hit a TypeError. I've attached the error message  below.
[error_typeError.txt](https://github.com/BitCurator/bc_to_aspace_toolkit/files/3091244/error_typeError.txt)

**Comment by kamwoods** [comment]
Should now be resolved in master.

**Comment by kamwoods** [comment]
No further errors reported. Closing.
