### ISSUE TITLE
bc_to_aspace.py breaks if no DFXML file available

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#17]
bc_to_aspace.py breaks when running on a project set that does not have DFXML.

**Comment by kamwoods** [comment]
Yes, the most recent version of the code *requires* that you have a DFXML file, and *requires* that you get the dates from it. In short, it only processes disk images, not content that has been parsed from a directory. The code should be modified to gracefully handle cases where a DFXML file is not available, by pulling dates from the Siegfried output and warning the user that if - for some reason - they produced this metadata from a disk image without producing a DFXML file, the dates will reflect the date at time of extraction.

**Comment by laissezfarrell** [comment]
Nice. Yes, that behavior would be more clear. I tried also to provide it a DFXML file created with walk_to_dfxml.py, but that failed as well (see issue 19).

**Comment by kamwoods** [comment]
Related to issue 19, this should be *partially* fixed. DFXML output produced by walk_to_dfxml.py should now work, but logic needs to be added to handle cases where no DFXML file is found. In progress.

**Comment by shauntru** [comment]
Following the instructions using the sample disk image example led to this error for me. No DFXML was generated by brunnhilde so the bc_to_as.py script broke.

**Comment by kamwoods** [comment]
A fix is incoming for the script to back off to using Siegfried timestamps if no dfxml is available. However, this example assumes that brunnhilde is functioning correctly; the command:

brunnhilde.py -z -b --tsk_imgtype ewf --tsk_fstype fat --tsk_sector_offset 1 -d nps-2010-emails.E01 /home/bcadmin brunnhilde-reports

should generate a dfxml.xml file in brunnhilde-reports. If you don't see that file, you may be using an older version of brunnhilde, or something else has gone wrong. Can you tell me a little bit more about what you're seeing when you run brunnhilde?

**Comment by shauntru** [comment]
Yes, I'm pretty positive that I need to update BC. I ran that exact command. Let me run through it again and see if there are any suspect errors, though I don't remember any.

**Comment by kamwoods** [comment]
Ok. Leaving this open for now. Update coming soon to provide the option of using Siegfried timestamps if the dfxml is missing or not needed (e.g. when processing a directory of files).

**Comment by kamwoods** [comment]
Script has been modified to warn the user when a DFXML file is not present, and provides two options: skip to the next dataset, or continue processing using Siegfried timestamps. The rationale here is that a given project folder may contain more than one dataset, and there may be a mix of datasets with and without DFXML files in them.

**Comment by kamwoods** [comment]
No further errors reported. Closing.
