### ISSUE TITLE
Script seems to hang when trying to match on existing repo code

### ISSUE THREAD

**Issue by noahgh221** [BitCurator/bc_to_aspace_toolkit#18]
In testing, we created a directory name that matched our repository code (Rubenstein Library).  We intended to load objects into an existing repository.  The script seemed to hang on the "Processing project folder..." step for at least several minutes.

**Comment by laissezfarrell** [comment]
Here is output from the console as it hangs. 

[error_hangs.txt](https://github.com/BitCurator/bc_to_aspace_toolkit/files/3091337/error_hangs.txt)

**Comment by yinglongz** [comment]
How large were the files that you attempted to upload?

**Comment by laissezfarrell** [comment]
In the example attached below, the entire Brunnhilde_reports directory was ~250MB, but that included the carved files from the disk image. But when we ran it using "test_repository" as the directory name, the same 250MB directory did not hang, and runs quite quickly.

[error_hangs.txt](https://github.com/BitCurator/bc_to_aspace_toolkit/files/3091472/error_hangs.txt)

**Comment by kamwoods** [comment]
There's no debug / error handling in the block of code that follows that message, yet. Needs to be modified to make it a bit easier to figure out where this might be going wrong.

**Comment by kamwoods** [comment]
Possibly fixed in latest master / release (v0.0.6). Can you retest?

**Comment by noahgh221** [comment]
Tested again this morning after grabbing most recent updates to this repo.  I tested with the included sample disk image. The script now seems to hang on processing the project folder directory.

![image](https://user-images.githubusercontent.com/7328518/56427305-5d7c9c80-6289-11e9-9151-f95bf679176b.png)

**Comment by noahgh221** [comment]
In looking at the script, it seems like it's looping over all archival objects in an ASpace repo, grabbing the response, and checking to see if the input ref_id matches the ref_id of an existing archival object?

https://github.com/BitCurator/bc_to_aspace_toolkit/blob/master/bc_to_as.py#L182

With close to a million archival objects in our repo, this seems like it could take a long time to check all of them for a matching ref_id (maybe why the script is hanging?)

There is a way to get archival objects directly by ref_id using a 'find_by_id' endpoint:
https://archivesspace.github.io/archivesspace/api/#find-archival-objects-by-ref_id-or-component_id

This might be more efficient.

This assumes I'm interpreting the script correctly.  Apologies if I'm off base here.

**Comment by yinglongz** [comment]
Hi Noah,

Yes, you are right. The script will loop over all the archival objects. I will check this API and make this script run more efficiently.

Thanks,
Yinglong


________________________________

**Comment by noahgh221** [comment]
Thanks! Here's an example of a script we use that uses 'find_by_id' to lookup archival objects by ref_id

https://github.com/duke-libraries/archivesspace-duke-scripts/blob/master/python/duke_update_archival_object.py#L82

**Comment by yinglongz** [comment]
Thanks, Noah!


________________________________

**Comment by kamwoods** [comment]
Approved merge from @yinglongz. @noahgh221 this should now be resolved in master.

**Comment by noahgh221** [comment]
Thanks! Will try to test again soon.

**Comment by noahgh221** [comment]
Tested again and this appears to be working. Thanks!
