### ISSUE TITLE
bc_to_aspace.py Key Error with DFXML generated from walk_to_dfxml.py

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#19]
For a set of files that had no disk image (cloud transfer), I ran walk_to_dfxml.py to generate DFXML for the materials. When running bc_to_aspace.py on that set of files, I got the attached KeyError...perhaps because there is no <volume> object in the DFXML file.

[keyerror.txt](https://github.com/BitCurator/bc_to_aspace_toolkit/files/3091330/keyerror.txt)

**Comment by yinglongz** [comment]
Hi Farrell,

Thanks for helping test the script. Is it possible that you could share the DFXML file with us for debuging the code?

Best,
Yinglong

**Comment by laissezfarrell** [comment]
I had to add a TXT extension so that GitHub would allow me to attach it. It was simply 'dfxml.xml' when running the script.
[dfxml.xml.txt](https://github.com/BitCurator/bc_to_aspace_toolkit/files/3091448/dfxml.xml.txt)

**Comment by yinglongz** [comment]
I think the dfxml.xml generated by walk_to_dfxml.py has a different schema from the one created by Siegfried.

**Comment by kamwoods** [comment]
This is linked to the other issue. The script in its current state expects metadata produced from a disk image, so always expect to find a volume (line 364 of bc_to_as.py). Again to handle all cases the script should be modified to determine whether or not the volume label is present and perform the appropriate parse as needed.

**Comment by kamwoods** [comment]
Likely fixed in latest master / release (v0.0.6). Can your retest?

**Comment by kamwoods** [comment]
Script has been modified to warn the user when a DFXML file is not present, and provides two options: skip to the next dataset, or continue processing using Siegfried timestamps. The rationale here is that a given project folder may contain more than one dataset, and there may be a mix of datasets with and without DFXML files in them.

**Comment by kamwoods** [comment]
No further errors reported. Closing.
