### ISSUE TITLE
Do not create ref_id values for imported archival objects (let ASpace mint them)

### ISSUE THREAD

**Issue by noahgh221** [BitCurator/bc_to_aspace_toolkit#24]
Currently, when bc_to_aspace.py creates new archival objects in ArchivesSpace it supplies a ref_id value based on the project directory name and subdirectory names within the /project directory. The ref_id values created by the script are inconsistent with those that are auto-generated by ArchivesSpace when archival objects are created "normally" in the staff interface. I would prefer to allow ArchivesSpace to mint ref_ids (UUIDs, I think) for objects that are created using the bc_to_aspace.py script. 

I think this could be done by just removing the ref_id values from the API POST.

Here maybe?: https://github.com/BitCurator/bc_to_aspace_toolkit/blob/58956ef04f0ab79a7da4667e97ac09fb599568ab/bc_to_as.py#L411

**Comment by kamwoods** [comment]
Ok, marking to be fixed. It looks like the behavior for file-level-equivalent ref_ids was never explicitly defined in the original spec at: 

https://docs.google.com/document/d/1-pU__nBYSgjHhfcxYhQLdci9rxSgo1XiXpLEFgQSkCE/edit?usp=sharing

In issue #7 the original implementer noted:

"The script will use the name of the project folder as a ref_id to match existing archival objects in ArchivesSpace. If an existing archival object is identified, all the file-level components will be posted as the children of the identified archival object"

Does that still hold?

**Comment by yinglongz** [comment]
Got it. I will fix it soon.

**Comment by noahgh221** [comment]
@kamwoods , that still holds. I think our idea was that if you wanted to import descriptive components as children of some parent already in ASpace, you could create a parent directory using the ref_id of the parent component just to serve as a match point.  I think that's still desirable, although making the archival object ID (part of the URI)  the match point might make more sense in hindsight...

Either way, I don't see any reason to have the script create ref_ids for imported archival objects.

There are some odd uniqueness constraints on ref_ids in ASpace.  They must be unique within a resource record, but don't have to be unique across the system. So, minting them outside of ASpace could lead to cases where there are duplicate ref_ids in different resource records.  We've actually run into this at Duke.

**Comment by kamwoods** [comment]
Fixed - merged in update from yinglongz

**Comment by kamwoods** [comment]
No further errors reported. Closing.
