### ISSUE TITLE
bc_to_aspace.py breaks if DFXML doesn't have mtimes

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#26]
Testing the script on a number of different disk image types, ran across an error where the script fails. Here is the relevant Traceback:

`Traceback (most recent call last):
  File "/usr/local/bin/bc_to_as.py", line 4, in <module>
    __import__('pkg_resources').run_script('bc-to-aspace-toolkit==0.0.6', 'bc_to_as.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/bc_to_aspace_toolkit-0.0.6-py3.6.egg/EGG-INFO/scripts/bc_to_as.py", line 449, in <module>
  File "/usr/local/lib/python3.6/dist-packages/bc_to_aspace_toolkit-0.0.6-py3.6.egg/EGG-INFO/scripts/bc_to_as.py", line 374, in run_session
ValueError: max() arg is an empty sequence`

Looking at the lines referenced in the script, it seems to break because the DFXML file has no mtime elements. 

The disk image that this came from is an EWF image created in Guymager of an optical disc, which is not a standard part of our workflow, so **this may be an edge case**

**Comment by laissezfarrell** [comment]
Removing the DFXML file and running the script again resulted in the script using Siegfried timestamps to create the ASpace components.

**Comment by kamwoods** [comment]
Ok. The second comment is the expected behavior. For the first, we should add some exception handling. If mtime isn't available, do you have a preference for what happens?

**Comment by laissezfarrell** [comment]
I suppose something similar to when there isn't DFXML at all. So, a message like, "DFXML doesn't include modified times. Would you like to rely on Siegfried values? y/N"

**Comment by kamwoods** [comment]
Ok. In progress.

**Comment by kamwoods** [comment]
Fixed and merged to master from branch FIX/dateexp.
