### ISSUE TITLE
date expression formatted oddly

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#27]
Dates for the created Archival Object components are formatted correctly except for the Expression part. See attached screencap for a visual representation, but the Expression field should be the range of years (in the attached example, should be 1980-1990 for inclusive dates). 

![dates](https://user-images.githubusercontent.com/1068952/58733496-a82e2000-83c2-11e9-9c9b-16616705db4c.JPG)

**Comment by kamwoods** [comment]
Noted, bug in script. Will fix.

**Comment by kamwoods** [comment]
Fixed and merged to master from branch FIX/dateexp.
