### ISSUE TITLE
Unknown file formats are reported as 'nan'

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#28]
When there are formats Siegfried could not identify, a count of those files is being recording in the ArchivesSpace Physical Description note as "Number of nan: 72."

Should either be "number of unidentified files: 72" or left out entirely.

**Comment by kamwoods** [comment]
Will fix.

**Comment by kamwoods** [comment]
Fix in merge to master. Now checks for null value in Brunnhilde formats.csv, and reports "unidentified files".
