### ISSUE TITLE
Recurse through _brunnout directories

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#4]
It would be helpful if the script could recurse through a default Brunnhilde output directory to find the files it needs (formats.csv and siegfriend.csv, which exist in different parts of the default Brunnhilde output directory). We would envision executing this script on a set of Brunnhilde outputs and it would save time if we could simply copy the entire _brunnout directory to the Repository/Project directories, rather than hunting for the individual files themselves and copying those to repository/project.

**Comment by yinglongz** [comment]
Thanks for the feedback! Will address this issue soon.

**Comment by EagleRock1313** [comment]
Agreed.

**Comment by kamwoods** [comment]
Fixed in a past release. Closing.
