### ISSUE TITLE
Extent types

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#5]
Script should POST extent type as Bytes. Currently, the script creates extent notes in bytes, but picks "Megabytes" as the extent type.

**Comment by yinglongz** [comment]
Thanks! Will fix it.

**Comment by kamwoods** [comment]
Fixed in merge via Yinglongz. Closing.

**Comment by kamwoods** [comment]
Apologies, closed this prematurely. It looks like the ArchivesSpace API *cannot* take bytes as the extent type, only megabytes and up. When trying to post with the current version, the following error occurs:

  [STATUS] Processing result for SET1:
{'error': {'children/0/extents/0/extent_type': ["Invalid value 'bytes'.  Must be one of: cassettes, cubic_feet, gigabytes, leaves, linear_feet, megabytes, photographic_prints, photographic_slides, reels, sheets, terabytes, volumes"]}, 'warning': None, 'invalid_object': '#
...(error continues)

This seems like a bad design choice on the part of ArchivesSpace, but either way the quick fix here is to simply do the calculation on this end and continue to report megabytes.

**Comment by kamwoods** [comment]
Reverted and modified in merge from FIX/filesizes. Now reports total_file_size / 1024 to two decimal places.

**Comment by kamwoods** [comment]
Clearly I did a bad math. *Now* reports total_file_size / 1048576 to two dec. Fixed in last push. Closing.
