### ISSUE TITLE
Specify target resource

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#6]
In most cases, we’d expect to use this script to post file-level components to existing resource records in ArchivesSpace, not create new resource records. To do this, it would be helpful if the script could prompt the user for some identifier (ASpace resource record identifier, eadid, or resource record URI) for the target resource to which it will attach archival object records. Changing this behavior would make the script useful in processing iterative additions to an existing collection.

**Comment by yinglongz** [comment]
The script will use the name of the project folder as a ref_id to match existing archival objects in ArchivesSpace. If an existing archival object is identified, this script will check whether an existing resource is associated with this archival object. If a specific resource is also found, all the file-level components will be posted as the children of the identified archival object without creating any new resource records.

**Comment by kamwoods** [comment]
Any further discussion on this?

**Comment by kamwoods** [comment]
Closing as this repo is end-of-life and will be archived.
