### ISSUE TITLE
specify series 'wrapper' or label

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bc_to_aspace_toolkit#7]
Script currently creates a generic parent archival object labeled 'file' to hold the more granular objects (also labeled 'files'). It would be helpful if the aggregate object created could be specified in the script at runtime (e.g. “Born-digital accession 2018-0001” or something…). Alternatively, it might be simpler to not create this parent archival object via the script and instead prompt for an identifier of an existing archival object in ASpace that can serve as the parent or the newly created archival objects .

This script does something like that, prompting for parent AO record IDs, and creating linked AO and DO records of the parent: https://github.com/duke-libraries/archivesspace-duke-scripts/blob/master/python/duke_create_ao_and_do.py using this endpoint of the Aspace API: https://archivesspace.github.io/archivesspace/api/#batch-create-several-archival-objects-as-children-of-an-existing-resource

**Comment by yinglongz** [comment]
The script will use the name of the project folder as a ref_id to match existing archival objects in ArchivesSpace. If an existing archival object is identified, all the file-level components will be posted as the children of the identified archival object.

**Comment by kamwoods** [comment]
Leaving this open as of 4/5/19. Any further follow up?

**Comment by yinglongz** [comment]
In archivesspace APIs, the parameter has to be set as “file”. I tried to change “file” to “files”, but it doesn’t work (got error messages from APIs).

**Comment by kamwoods** [comment]
Closing as this repo is end-of-life and will be archived.
