### ISSUE TITLE
Siegfried returns incorrect modified date - current processing date

### ISSUE THREAD

**Issue by EagleRock1313** [BitCurator/bc_to_aspace_toolkit#8]
The Siegfried .csv returns a modified date which is the current processing date.  This does not reflect the original file metadata, and cascades errors effecting years/extent calculations that are then exported to ArchiveSpace.  The range of years is reported incorrectly and exported to ArchiveSpace.  The fiwalk .dfxml file appears to retain correct file dates for all files, compressed archive (zip) and non archived files.

It would be helpful to convert .dfxml output file to .csv for processing correct metadata and export.

**Comment by laissezfarrell** [comment]
In processing disk images, Brunnhilde uses TSK to extract logical files which are then passed through Siegfried. TSK doesn't retain file system dates from the disk image's file system(s).

Converting DFXML output to CSV would be useful, but would that be a better as a suggested change to the Brunnhilde toolset itself?

**Comment by EagleRock1313** [comment]
Hi Farrell,
Yes, having Brunnhilde do the .dfxml to .csv is one way to approach it. However, this tool's purpose is export Metadata to ArchiveSpace.  Having a tool map the ArchiveSpace API to .csv outputs is quite useful.  Thoughts?

**Comment by kamwoods** [comment]
Merged branch via Yinglongz disregarding Siegfried dates and parsing dates from DFXML instead. Closing.
